Repository bodyBudy/bodyBuddy, pull requests merged in 2022-08, with the labels that each got.

#108 fix: fix type error
  components/layout/chat/Talks.tsx
  pages/chat/[id].tsx
Labels: bug, fix

#113 Fix Review Type in firebase.ts
  api/firebase.ts
  api/firebase.type.ts
Labels: fix

#114 Edit Backend Server(Custom Server, firebase Setting)
  .gitignore
  api/firebase.ts
  package-lock.json
  package.json
  pages/oauth/kakao/index.tsx
  pages/signUp/member/index.tsx
  redux/userSlice.ts
  server/index.ts
  yarn.lock
Labels: feat, server

#115 verify jwt token (in server)
  api/firebase.ts
  package-lock.json
  package.json
  pages/oauth/kakao/index.tsx
  pages/signUp/checkCategory.tsx
  redux/trainerSlice.ts
  redux/userSlice.ts
  server/index.ts
  server/jwtToken/index.ts
  yarn.lock
Labels: feat, server

#118 Add useGetUserInfo hook
  hooks/useCheckAuth.ts
  hooks/useGetUserInfo.ts
Labels: feat

#120 Add useInfiniteScroll Hook
  components/layout/community/Post/index.tsx
  components/layout/community/Post/post.d.ts
  hooks/useInfiniteScroll.ts
  pages/community/index.tsx
  yarn.lock
Labels: feat, common

#124 Modify overall Index page
  api/firebase.ts
  components/common/career/index.tsx
  components/common/profile/index.tsx
  components/layout/index/TrainerItem.tsx
  components/layout/trainer/TrainerBody.tsx
  components/layout/trainer/TrainerHeader.tsx
  components/layout/trainer/TrainerImages.tsx
  components/layout/trainer/edit.tsx
  components/layout/trainer/trainer.d.ts
  pages/index.tsx
  pages/trainer/[id]/edit.tsx
  pages/trainer/[id]/index.tsx
Labels: fix, feat
