Repository bodyBudy/bodyBuddy, pull requests merged in 2022-07, with the labels that each got.

#51 Review Page CSS Styling
  components/common/buttongroup/index.tsx
  components/common/buttongroup/styledButtonGroup.ts
  components/common/itemgroup/index.tsx
  components/common/itemgroup/styledItemGroup.ts
  components/common/rating/index.tsx
  components/common/title/styledTitle.ts
  components/common/uploader/index.tsx
  components/layout/community/Comment.tsx
  components/layout/review/Review.tsx
  components/review/Review.tsx
  data/index.ts
  data/service.ts
  pages/community/[id].tsx
  pages/community/index.tsx
  pages/profile/posts/[id].tsx
  pages/review/index.tsx
  public/assets/common/checkboxSquare-checked.svg
  public/assets/common/checkboxSquare.svg
  styles/globals.ts
Labels: design

#54 #45 feat: styling chat pages
  components/common/nav/index.tsx
  components/layout/Layout.tsx
  components/layout/chat/GymInfo.tsx
  components/layout/chat/Talk.tsx
  components/layout/chat/TrainerInfo.tsx
  components/layout/chat/index.ts
  pages/chat/[id].tsx
  pages/chat/list.tsx
  pages/chat/meeting.tsx
  public/assets/common/arrow-bottom.svg
  public/assets/common/arrow-left-purple.svg
  public/assets/common/chat-blank.svg
  public/assets/common/chat.svg
  public/assets/common/doc-blank.svg
  public/assets/common/doc.svg
  public/assets/common/home-blank.svg
  public/assets/common/home.svg
  public/assets/common/send-button.png
  public/assets/common/user-blank.svg
  public/assets/common/user.svg
  styles/emotion.d.ts
  styles/globals.ts
  styles/theme.ts
  yarn.lock
Labels: design

#55 Design trainer page
  components/layout/trainer/TrainerBody.tsx
  components/layout/trainer/edit.tsx
  components/layout/trainer/trainer.d.ts
  pages/trainer/[id]/edit.tsx
  pages/trainer/[id]/index.tsx
Labels: design

#59 Implement index page function
  components/common/checkbox/checkbox.d.ts
  components/common/checkbox/index.tsx
  components/common/radio/index.tsx
  components/common/radio/radio.d.ts
  components/layout/index/DetailOption.tsx
  components/layout/index/Option.tsx
  components/layout/index/TrainerItem.tsx
  data/city.ts
  pages/index.tsx
Labels: feat, design

#61 Implement range component
  components/common/range/index.tsx
  components/common/range/range.d.ts
  components/common/range/styledRange.ts
  components/layout/index/DetailOption.tsx
  components/layout/index/Option.tsx
  pages/index.tsx
Labels: feat

#63 Fix Common Component
  components/common/button/button.d.ts
  components/common/button/index.tsx
  components/common/button/styledButton.ts
  components/common/buttongroup/buttonGroup.d.ts
  components/common/buttongroup/index.tsx
  components/common/buttongroup/styledButtonGroup.ts
  components/common/itemgroup/index.tsx
  components/common/meta/index.tsx
  components/common/meta/meta.d.ts
  components/common/meta/styledMetaContainer.ts
  components/common/modal/styledModal.ts
  components/layout/community/Comment.tsx
  components/layout/community/Post.tsx
  components/layout/review/Review.tsx
  data/field.ts
  data/index.ts
  package-lock.json
  pages/community/[id].tsx
  pages/community/index.tsx
  yarn.lock
Labels: bug, common

#67 Implement profile component
  components/common/profile/index.tsx
  components/common/profile/profile.d.ts
  components/common/profile/styledProfile.tsx
  components/layout/trainer/TrainerHeader.tsx
  components/layout/trainer/edit.tsx
Labels: feat, design, common

#75 Add sessionStorage to index page and Modify review component of trainer page
  components/layout/index/DetailOption.tsx
  components/layout/trainer/TrainerBody.tsx
  pages/index.tsx
  public/assets/common/padlock.svg
Labels: feat

#81 Create career uploader component
  components/common/career/career.d.ts
  components/common/career/index.tsx
  components/common/career/styledCareer.ts
  components/layout/trainer/edit.tsx
  components/layout/trainer/trainer.d.ts
  pages/trainer/[id]/edit.tsx
Labels: feat, design, common

#84 Image Upload/Get
  api/firebase.ts
  api/firebase.type.ts
  components/common/uploader/index.tsx
  components/layout/community/Comment/index.tsx
  components/layout/community/Post.tsx
  components/layout/community/Post/index.tsx
  components/layout/community/Post/post.d.ts
  next.config.js
  package-lock.json
  pages/community/index.tsx
  pages/community/posting.tsx
  yarn.lock
Labels: feat, common

#86 feat: #85 fetch chats and show
  api/firebase.ts
  api/firebase.type.ts
  components/layout/chat/Talks.tsx
  components/layout/chat/index.ts
  package.json
  pages/chat/[id].tsx
  tsconfig.json
  yarn.lock
Labels: feat

#87 Filter trainer list by detail options and Get trainer data
  api/firebase.ts
  components/common/cost/cost.d.ts
  components/common/cost/index.tsx
  components/common/cost/styledCost.ts
  components/layout/trainer/ImageViewer.tsx
  components/layout/trainer/TrainerBody.tsx
  components/layout/trainer/TrainerHeader.tsx
  components/layout/trainer/edit.tsx
  components/layout/trainer/trainer.d.ts
  pages/index.tsx
  pages/trainer/[id]/edit.tsx
  pages/trainer/[id]/index.tsx
Labels: feat, design

#89 Community Page - DB update
  api/firebase.ts
  api/firebase.type.ts
  components/common/buttongroup/buttonGroup.d.ts
  components/common/buttongroup/index.tsx
  components/layout/community/Comment/index.tsx
  components/layout/community/ItemGroup/index.tsx
  components/layout/community/ItemGroup/itemgroup.d.ts
  components/layout/community/ItemGroup/styledItemGroup.ts
  components/layout/community/Post/index.tsx
  components/layout/community/Post/post.d.ts
  components/layout/review/Review.tsx
  pages/community/[id].tsx
  pages/community/index.tsx
  pages/community/posting.tsx
Labels: feat

#91 setting redux persist
  components/layout/Layout.tsx
  components/layout/SEO.tsx
  package-lock.json
  package.json
  redux/store.ts
  yarn.lock
Labels: chore, feat

#96 Update trainer profile
  api/firebase.ts
  components/layout/trainer/TrainerBody.tsx
  components/layout/trainer/edit.tsx
  components/layout/trainer/trainer.d.ts
  pages/trainer/[id]/edit.tsx
  pages/trainer/[id]/index.tsx
Labels: feat

#102 Get all trainer data
  api/firebase.ts
  pages/index.tsx
Labels: feat

#103 Separate Review Component
  api/firebase.ts
  components/common/buttongroup/buttonGroup.d.ts
  components/common/review/index.tsx
  components/common/review/review.d.ts
  components/common/review/styledReview.ts
  components/common/title/index.tsx
  components/common/title/title.d.ts
  components/layout/community/Post/post.d.ts
  pages/community/[id].tsx
  pages/community/index.tsx
  pages/community/posting.tsx
  pages/profile/posts.tsx
  pages/review/index.tsx
Labels: fix, common
